authorName: fyh
experimentName: ConSK-GCN_Multi_Knowledge_Meld
trialConcurrency: 2
maxExecDuration: 3d
maxTrialNum: 50
#choice: local, remote, pai
trainingServicePlatform: local
searchSpacePath: search_space.json
#choice: true, false
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner, GPTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
trial:
  command: D:/Anaconda/python  train_multi.py
  codeDir: ../
  gpuNum: 1


